### ISSUE TITLE
새로운 시험지가 올라올 경우 메뉴에 최신글 아이콘 표시

### ISSUE THREAD

**Issue by socialskyo** [YJSoft/xe-module-exam#17]
메뉴 새글  모듈과 연동이 될런지는 모르겠지만 가능하다면 메뉴에도 N/U 아이콘이 붙으면 좋겠습니다.
https://xetown.com/index.php?&mid=rxe_point&search_keyword=새글&search_target=title_content&document_srl=12592

늘 감사합니다.

**Comment by YJSoft** [comment]
해당 자료에서 수정이 필요한 부분으로 파악됩니다.(외부에서 New/Update를 붙이기 힘든 구조입니다)
