### ISSUE TITLE
문제출제 및 수정에서 '지문'의 '머리글'이 전달되지 않는 문제 수정

### ISSUE THREAD

**Issue by cydemo** [YJSoft/xe-module-exam#18]
exam.controller.php 파일
#245행
$args->description_title = htmlspecialchars($params->**description_title**, ENT_COMPAT | ENT_HTML401, 'UTF-8', false);
에서처럼 파라미터값이 잘못 코드화되어 있었습니다.

$args->description_title = htmlspecialchars($params->**q_description_title**, ENT_COMPAT | ENT_HTML401, 'UTF-8', false);
으로 고쳤더니 DB에 입력도 잘 되고 스킨 상에서도 잘 출력됩니다.

근데 이거 그냥 $args->description_title = **escape**($params->q_description_title); 으로 간소화해도 되지 않나요? 아... XE에선 안 되던가요;;;

**Comment by YJSoft** [comment]
일단 변수명만 수정해두고 escape 함수로 변환하는건 다른 이슈에서 처리합니다.
