### ISSUE TITLE
시험기간 출력 방식 간소화

### ISSUE THREAD

**Issue by cydemo** [YJSoft/xe-module-exam#24]
자꾸 올려서 죄송합니다. 바쁘실 텐데ㅜㅜ
스킨 작업을 하다보니까 눈에 들어오는 것들이 있어서요.

현재 스킨에서 '시험기간'은 **exam.item.php 355행의 getExamDate($format = 'Y.m.d H:i') 함수**를 받아서 출력하는 걸로 되어 있는데요.
이 부분이 너무 깁니다.
2020.05.15 12:00 ~ 2020.05.15 13:00 이런 식으로요.
이용자 입장에서는 시험지 목록에서 시험기간이 표시항목으로 있을 경우 기간 식별이 어렵고 시각적 피로감마저 느낄 수 있습니다.
그래서 이 부분을 2020.05.15 12시 ~ 13시 같은 식으로 줄여서 출력하면 어떨까 하는 생각이 들었습니다.

시작일시와 종료일시의 문자열을 비교해서 중복되는 형식을 생략해서
날짜 표기를 간소화하도록 getExamDate() 함수를 아래와 같이 수정하면 어떨까 합니다.

	function getExamDate()
	{
		if ( !$this->isDate() )
		{
			$str = Context::getLang('exam_no_end_date');
		}
		else
		{
			$start_date = $this->get('start_date');
			$end_date = $this->get('end_date');
			// 조건 설정 : 시작과 종료의 년도가 현재 년도와 같은지
			$this_year = substr($start_date, 0, 4) === date('Y') && substr($end_date, 0, 4) === date('Y');

			// 시작과 종료 모두 H시 정각이라면
			if ( substr($start_date, 10, 2) === '00' && substr($end_date, 10, 2) === '00' )
			{
				// 시작 시각은 시까지만 출력
				$startline = $this_year ? zdate($start_date, 'm.d H시'): zdate($start_date, 'Y.m.d H시');
				$str = $startline . ' ~ ';
				// 시작과 종료가 같은 시각이라면
				if ( substr($start_date, 0, 10) === substr($end_date, 0, 10) ) $str = $startline;
				// 일자까지 같다면
				elseif ( substr($start_date, 0, 8) === substr($end_date, 0, 8) ) $str .= zdate($end_date, 'H시');
				// 년도만 같다면
				else if ( substr($startline, 0, 4) === substr($end_date, 0, 4) ) $str .= zdate($end_date, 'm.d H시');
				// 년도가 다르다면
				else $str .= $this_year ? zdate($end_date, 'm.d. H시') : zdate($end_date, 'Y.m.d. H시');
			}
			else
			{
				// 시작 시각은 분까지 출력
				$startline = $this_year ? zdate($start_date, 'm.d H시i분'): zdate($start_date, 'Y.m.d H시i분');
				$str = $startline . ' ~ ';
				// 시작과 종료가 같은 시각이라면
				if ( substr($start_date, 0, 12) === substr($end_date, 0, 12) ) $str = $startline;
				// 시까지 같다면
				elseif ( substr($start_date, 0, 10) === substr($end_date, 0, 10) ) $str .= zdate($end_date, 'i분');
				// 일자까지 같다면
				elseif ( substr($start_date, 0, 8) === substr($end_date, 0, 8) ) $str .= zdate($end_date, 'H시i분');
				// 년도만 같다면
				else if ( substr($startline, 0, 4) === substr($end_date, 0, 4) ) $str .= zdate($end_date, 'm.d H시i분');
				// 년도가 다르다면
				else $str .= $this_year ? zdate($end_date, 'm.d H시i분'): zdate($end_date, 'Y.m.d H시i분');
			}
		}
		return $str;
	}

**Comment by YJSoft** [comment]
기존 스킨과 호환성 유지를 위해, `$short`가 `TRUE`일때만 해당 코드를 사용해 기간을 출력합니다.
(기본값은 `FALSE`)
