### ISSUE TITLE
getAllQuestionPoint 함수 수정

### ISSUE THREAD

**Issue by cydemo** [YJSoft/xe-module-exam#27]
exam.item.php에서 총 배점이 0일 경우 100으로 출력하도록 되어 있습니다.
각 문제에 배점이 하나도 배정되어 있지 않거나, total_point 계산에 실패했을 경우에 0점이 됩니다.
이것을 굳이 100점으로 표시할 이유는 없어 보입니다.
뿐만 아니라 경우에 따라 100점 만점이 아닌 경우도 있기 때문에 100점으로 고정하는 것은 더욱 더 필요가 없어보입니다.

exam.item.php 566행
return $this->get('total_point') == 0 ? 100 : $this->get('total_point');
대신에
**return $this->get('total_point');**
으로 바로 출력값을 가져오는 것이 타당해보입니다.

**Comment by YJSoft** [comment]
모든 문제에 배점이 지정되어 있지 않은 경우 예전 방식대로 동작합니다.(전체 배점을 100으로 가정후 계산)
따라서 해당 함수도 100을 리턴하도록 구성했는데, 이경우 아예 구분이 불가능한 문제점이 있어 getAllQuestionPoint 자체는 0을 리턴할수 있도록 변경해 두었습니다.

다만 기존 시험지를 불러왔을때 총 배점이 0점으로 표시될수 있으며 이점은 따로 수정될 예정입니다.
